os: linux
dist: xenial
language: generic
# sudo: false

addons:
  apt:
    packages:
      - libc6-i386

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  jobs:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=clisp
    - LISP=ecl
    - LISP=alisp
    # - LISP=cmucl

jobs:
  allow_failures:
    - env: LISP=clisp
    - env: LISP=abcl
    - env: LISP=ecl
    - env: LISP=alisp
    # - env: LISP=cmucl

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
  - ros install prove
  - ros install bordeaux-threads

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

script:
  - run-prove cl-reex-test.asd